# Generated by Django 6.1 on 2026-08-10 04:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('language_code', models.CharField(blank=True, max_length=16)),
                ('is_allowed', models.BooleanField(default=False, help_text='Only allowed users can generate images.', verbose_name='Allowed')),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('prompt', models.TextField()),
                ('image_size', models.CharField(default='1:1', max_length=16)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('queuing', 'Queuing'), ('generating', 'Generating'), ('success', 'Success'), ('fail', 'Failed')], db_index=True, default='waiting', max_length=16)),
                ('result_url', models.URLField(blank=True, max_length=1024)),
                ('fail_message', models.TextField(blank=True)),
                ('delivered', models.BooleanField(default=False, help_text='The result has been sent back to the Telegram chat.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Generation',
                'verbose_name_plural': 'Generations',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['state', 'delivered'], name='bot_generat_state_7520f4_idx')],
            },
        ),
    ]
