# Generated by Django 6.1 on 2026-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', help_text='Language the bot replies in.', max_length=2, verbose_name='Bot language'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, help_text='Raw locale reported by the Telegram client.', max_length=16, verbose_name='Telegram locale'),
        ),
    ]
