# Generated by Django 6.1 on 2026-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_encrypt_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='cleanup_message_ids',
            field=models.JSONField(blank=True, default=list, help_text='Interim chat messages to delete once the result is delivered. Stored on the task so a restart still tidies the chat.'),
        ),
    ]
